config/routes.rb
Ftgg::Application.routes.draw do
  resources :ebs, only: [:index, :create, :show]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :ev_favorites, only: [:index, :create, :destroy]  
   
  root to: 'welcome#home'

  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  get 'events/search'

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="f_container">
		<div class="row">
			<div class="span4" id="about_us_links">
				<div class="row">
					<div class="span1">About Us</div>
				</div>
				<div class="row chevrons">
					<div class="span2"><a href="/about#contact">Contact</a></div>
					<div class="span2"><a href="/faq">FAQ</a></div>
				</div>
				<div class="row chevrons">
					<div class="span2">
						<a href="https://twitter.com/supatra.indhara" rel="external" target="_blank">Twitter</a>
					</div>
					<div class="span2"><a href="https://www.facebook.com/" rel="external" target="_blank">Facebook</a></div>
				</div>
			</div>
			<div class="span4 padded">
				&nbsp;
				<!--<div id="mc_embed_signup">
					<form action="" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="novalidate" target="_blank">
					<div class="newsletter-note">Join our mailing list!</div>
					<div class="mc-field-group">
						<input class="required email" id="mce-EMAIL" name="EMAIL" placeholder="Your Email Address" type="email" value="">
						<input name="u" type="hidden" value="4ee1aaad2e315a0de585af615">
						<input name="id" type="hidden" value="e85a9249f3">
						<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Submit">
					</div>
					</form>
				</div>-->
			</div>
			<div class="span4 pull-right">
				<div class="row padded">© 2013 Chance for Good.</div>
				<div class="row"><a href="/privacy">Privacy</a> | <a href="/terms">Terms of Use</a></div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="navbar-inner">
	<div class="h_container">
	    <div class="row">
		    <div class="span4">
			    <%= link_to 'CHANCE FOR GOOD', root_path, {id: "logo", class: 'brand'}%>	
			</div>
			<div class="span8">
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Events", 	events_path %></li>
						<li><%= link_to "Add Event", new_event_path %></li>
						<% if signed_in? %>
							<li><%= link_to "Import Events", ebs_path if current_user.admin? %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Bookmark", ev_favorites_path %></li>
									<li><%= link_to "My Events", ev_favorites_path %></li>
									<li><%= link_to "Event History", ev_favorites_path %></li>
									<li><%= link_to 'Profile', edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li><%= link_to 'Sign Out', signout_path, method: "delete" %></li>	
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Sign Up", 	signup_path %></li>
							<li><%= link_to "Log In", 	signin_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
    	</div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= content_for?(:title) ? yield(:title) : "FTGG Events" %></title>
	  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "FTGG Events" %>">
	  <%= stylesheet_link_tag "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.min.css" />
	  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
	  <%= csrf_meta_tags %>
		<!--[if lt IE 9]>
		<script src="assets/html5shiv.js"></script>
		<![endif]-->
	  <%= yield(:head) %>
	</head>	
	<body>
	<%= render "layouts/header"%>
	<div class="container">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
	</div>
	<%= render "layouts/footer"%>	
	</body>
</html>